openapi: '3.0.3'
info:
  title: 'Widget Management Application'
  description: 'Widget RESTful API Spec'
  version: '1.0'
servers:
  - url: http://127.0.0.1:5000/
components:
  schemas:
    Widget:
      # Definition of a "Widget" object
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          maximum: 64
        number_of_parts:
          type: integer
        created_date:
          type: string
        updated_date:
          type: string
      required:
        - "name"
        - "number_of_parts"
      example:
        name: "Widget 1"
        number_of_parts: 20
paths:
  /widgets:
    get:
      # GET /widgets
      description: 'Return all widgets'
      responses:
        '200':
          description: 'List with all the available widgets'
          content:
            'application/json':
              schema:
                # Returns an array of "Widget" elements
                type: array
                items:
                  $ref: '#/components/schemas/Widget'
  /widget/{name}:
    get:
      # GET /widget/{name}
      description: 'Return the details about the widget with the requested name'
      parameters:
        - name: name
          in: path
          description: 'Name of the widget to request'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'The requested widget'
          content:
            'application/json':
              schema:
                # Returns the requested widget
                $ref: '#/components/schemas/Widget'
        '404':
          description: 'Widget not found'  
    post:
      # POST /widget/{name}
      description: 'Add a new widget'
      parameters:
        - name: name
          in: path
          description: 'Name of the widget to create'
          required: true
          schema:
            type: string  
      requestBody:
        description: Details of the widget to add
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Widget'
      responses:
        '201':
          description: 'Widget successfully added'      
        '401':
          description: 'Non authorized to do this operation'  
        '400':
          description: 'Bad request'  
    put:
      # PUT /widget/{name}
      description: 'Update the details about the widget with the specified name'
      parameters:
        - name: name
          in: path
          description: 'Name of the widget to modify'
          required: true
          schema:
            type: string
      requestBody:
        description: New details of the widget to be modified
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Widget'    
      responses:
        '200':
          description: 'Widget successfully updated'
        '404':
          description: 'Widget not found'
    delete:
      # DELETE /widget/{name}
      description: 'Delete the widget with the specified name'
      parameters:
        - name: name
          in: path
          description: 'Name of the widget to delete'
          required: true
          schema:
            type: string       
      responses:
        '200':
          description: 'Widget successfully removed'         
        '404':
          description: 'Widget not found'         